version: "3.8"

services:
  
  app:
    build:
      context: .
      args:
        - IS_DEV=true
    image: portto_assignment
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - GIN_MODE=debug
      - PORT=8080
    entrypoint:
      - bash
      - -c
      - air -c .air.toml
   
    